
services:
  # GTD Spring App
  gtd:
    build:
      context: .
    container_name: gtd-spring-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskdb
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: senha
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    networks:
      - backend

  # MySQL do GTD
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
      MYSQL_USER: my_user
      MYSQL_PASSWORD: senha
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  # Moodle (Bitnami)
  moodle:
    image: bitnami/moodle:5.0
    container_name: moodle-app
    ports:
      - "8000:8080"
    environment:
      MOODLE_DATABASE_TYPE: mariadb
      MOODLE_DATABASE_HOST: moodle-db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_PASSWORD: moodle
    volumes:
      - moodle_data:/bitnami/moodle
      - moodle_modules:/bitnami/moodledata
    depends_on:
      - moodle-db
    networks:
      - backend

  # MariaDB para o Moodle
  moodle-db:
    image: mariadb:10.11
    container_name: moodle-db
    environment:
      MYSQL_ROOT_PASSWORD: moodle
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - moodle_db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql_data:
  moodle_data:
  moodle_modules:
  moodle_db_data:

networks:
  backend:
